* 200ok Talks

Resources to various talks given by 200ok team members at various
locations.


** Introduction to =organice=                           :alain:emacs:OrgMode:

*** Rationale

    This is a pre-recorded talk of Alain for the [[https://emacsconf.org/2019/schedule][EmacsConf 2019]] on
    November 2nd 2019.

*** Abstract

    Are you a fan of [[http://orgmode.org/][Org mode]]? If so, you probably want to have access
    to your Org files at any time - even when away from your computer.
    Or maybe you want to collaborate with other people who are not
    Emacs users themselves.

    organice is the solution for that!

    It is an implementation of Org mode without the dependency of
    [[https://www.gnu.org/software/emacs/][Emacs]]. It is built for mobile and desktop browsers and syncs with
    Dropbox and Google Drive.

    Please find the code of organice here:
    https://github.com/200ok-ch/organice

*** Recording

    The talk has been pre-recorded and is available on Youtube: [[https://www.youtube.com/watch?v=aQKc0hcFXCk]]


*** Slides

[[file:introduction_to_organice/organice_intro.org][./introduction_to_organice/organice_intro.org]]


** Introduction to ClojureScript and Functional Programming :alain:clojure:fp:
*** Rationale

This is a talk Alain gave at the [[https://www.meetup.com/de-DE/Web-Zurich/events/252786883][Web Zueri Meetup in Zurich,
Switzerland]] on July 24, 2018.

*** Abstract

The complexity of software is growing at an exponential rate. The
biggest challenge is the growing complexity of dynamic state which
makes it hard to reason about a system. There are many paradigms
aiming to ease the situation. To reduce incidental complexity
"Functional Programming" and "Code Hot-Reloading" have become much
talked about topics in the web development community.

In this talk, Alain will show you how to supercharge your development
setup with true code hot-reloading in a truly functional programming
language.

*** Recording

To be announced. The Web Zueri crew made a recording and will publish
it on their Youtube channel.

*** Slides

[[file:introduction_to_clojurescript_and_functional_programming][introduction_to_clojurescript_and_functional_programming]]



** Play Emacs like an instrument                           :alain:clojure:fp:

*** Rationale

 This is a talk Alain gave at the [[https://www.meetup.com/zh-clj-Zurich-Clojure-User-Group/events/249150421/][Clojure Meetup in Zurich, Switzerland]]
 on April 23, 2018.

*** Abstract

 Lean back and relax while enjoying a deep dive into the wonderful
 world of the Emacs editor. Emacs renaissance came with the advent of
 Clojure and undoubtedly is the most popular editor among Clojurians
 today. Of course there is a lot more you can do with Emacs, but much
 like playing an instrument, great skill only comes with practice.

 You neither need to be an Emacs user nor a Clojure Programmer and
 neither do you need to contemplate about becoming one either to enjoy
 this talk. Much like you don't become a professional musician by
 attending a concert, but it might very well be inspiring.

*** Recording

 The talk has been recorded and is available on Youtube: https://www.youtube.com/watch?v=gfZDwYeBlO4

*** Slides

[[file:play_emacs_like_an_instrument]]
